### ISSUE TITLE
Facebook callback goes to wrong server in a multi-server AWS stack

### ISSUE THREAD

**Issue by huminado** [jaredhanson/passport-facebook#104]
We have an AWS EC2 stack of several webservers running node.js/passport.  These servers are behind a NAT, and there's an Elastic Load Balancer which directs traffic in round-robin fashion to distribute load among the servers.

When there's a Facebook authentication, the callback response may go to the same server that issued the request, but sometimes it goes to the wrong server (because browsing traffic can be directed to any webserver in the stack).  So if we reduce the number of webservers to 1, everything works great.  If we increase the number of webservers and increase traffic, the client hangs waiting for the callback.

I'm looking for a best-practice way of addressing this use case.

EDIT1: I'm beginning to look into how to approach this problem using a server dedicated to handling the Facebook callback (which I'll call an authentication server).  For a Facebook authentication request on a webserver, the webserver has to make a request to the authentication server for it to do the Facebook authentication and respond with a Facebook token.  I'm not sure how the cookies get forwarded in this case (from the webserver to the authentication server) - I'm just somewhat new to node.js and passport programming.

EDIT2: The other alternative would be for AWS to provide support (if it's not already there - but I don't think it is) for a webserver to query the NAT to find out what outside port it's on, and the ELB to forward traffic according to specific port when given in the callback URL.

**Comment by ceejayoz** [comment]
Enable AWS ELB's sticky sessions or use a shared session store (redis, memcached, database-backed, etc.) for your app. This isn't something to solve via code.

**Comment by huminado** [comment]
Thanks again.  This issue is fully documented here:

http://stackoverflow.com/questions/27926635/facebook-authentication-callback-to-wrong-server-with-aws-elb-elastic-load-balan

Namely, the application was doing an auth request before having established a session.
