### ISSUE TITLE
undefined email in returned profile 

### ISSUE THREAD

**Issue by cjroebuck** [jaredhanson/passport-facebook#11]
When I receive the User Profile from Facebook, the emails array has one element inside, but its value is 'undefined'. 

Is it a bug or is FB just not sending back the email address. Email is really the only thing we can use to associate the account with another account so it's essential we can get this from Facebook.

Thanks

**Comment by Joe-Watson** [comment]
How to set Facebook CallbackURl in App Setting. Could you please navigate me?

**Comment by scroll17** [comment]
@Joe-Watson It exists where is "localhost"
<img width="1050" alt="image" src="https://github.com/jaredhanson/passport-facebook/assets/47834834/e6b8ee2a-1f27-45c4-9ab3-fbff79577d41">
