### ISSUE TITLE
Does isAuthenticated() only work when Session enabled?

### ISSUE THREAD

**Issue by demisx** [jaredhanson/passport-facebook#114]
Currently, I have session set to false. I am able to log in with Facebook, but `isAuthenticated()` returns false on each subsequent request. Is my understanding correct, that `isAuthenticated()` only works if I have passport session enabled and if session is disabled, I need to manage authorization access to routes myself? Thank you.

**Comment by jaredhanson** [comment]
Yes.  Page-based sites need session support to preserve login state.
