### ISSUE TITLE
Redirect URI - How to remove "#_=_" from Facebook Redirect?

### ISSUE THREAD

**Issue by niftylettuce** [jaredhanson/passport-facebook#12]
**UPDATE**: See [this comment](https://github.com/jaredhanson/passport-facebook/issues/12#issuecomment-40427410) towards end of this issue comment thread for the latest version of the fix for this issue.

---

Not sure how to fix this, since there isn't an immediate answer as to how to set the redirect URI.

Found this on SO: http://stackoverflow.com/questions/7693663/remove-from-the-facebook-redirect-url.

Also this will help to provide context: https://developers.facebook.com/bugs/196125357123225.

**Comment by k-j-kleist** [comment]
@arcanis: +1

**Comment by yozaira** [comment]
Thanks for the fix, guys! It was driving me crazy

**Comment by m3commish** [comment]
Where do I place the code?



// Remove the ugly Facebook appended hash
// <https://github.com/jaredhanson/passport-facebook/issues/12>
(function removeFacebookAppendedHash() {
  if (!window.location.hash || window.location.hash !== '#_=_')
    return;
  if (window.history && window.history.replaceState)
    return window.history.replaceState("", document.title, window.location.pathname);
  // Prevent scrolling by storing the page's current scroll offset
  var scroll = {
    top: document.body.scrollTop,
    left: document.body.scrollLeft
  };
  window.location.hash = "";
  // Restore the scroll offset, should be flicker free
  document.body.scrollTop = scroll.top;
  document.body.scrollLeft = scroll.left;
}());

**Comment by Ottiko** [comment]
When user try to log in with FB, then I redirect him to my web url "/fb", but this code is clear my "/fb" get param...

**Comment by BjarniLeifs** [comment]
I had this problem and tried a lot of things. 

How ever when I added website and hit quick start in the app (in website title bar on app site)
I saw : Setup the Facebook SDK for JavaScript

They said to put it after <body>  and  So I did.

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      YOUR_APP_ID,
      xfbml      : true,
      version    : 'v2.4'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>


Everything worked after what .. 

Since I'm using jwt and not session I had to add in the callback

app.get('/auth/facebook/callback', passport.authenticate('facebook', {
	session: false,
  	successRedirect : '/',
  	failureRedirect : '/login'
}));

Now I get the information from Facebook but some variable's undefined, but it is step forward.

Hope this works for you too :)

**Comment by Globik** [comment]
Епт, на дворе 2016 год, а до сих пор не исправили баг.

**Comment by cadilhac** [comment]
@niftylettuce For completeness, it would be good to add the query string to the url rewrite:

`return window.history.replaceState("", document.title, window.location.pathname + window.location.search);
`

**Comment by niftylettuce** [comment]
done @cadilhac

**Comment by rubilnik89** [comment]
Епт, на дворе середина 2017 года, а до сих пор не исправили баг.

**Comment by Globik** [comment]
А и не говори.

**Comment by vtrykoz** [comment]
ёпт, на дворе начало 2018 года, а до сих пор не исправили баг.

**Comment by Globik** [comment]
Баг не баг, а не покую ли как строка выглядет? Пить, есть не просит. Ее преобразовать можно с помощью windows.history или что-то в этом роде. Да мне просто лень это делать, да и не во всех браузерах сиё работает.

**Comment by Globik** [comment]
Че интересно так history.replacestate в файерфоксе почему-то не возымеет никакого действия, в ие не пробовал. В хроме отлично работает, на ура.

**Comment by nikitakotenko88** [comment]
2018... still

**Comment by Globik** [comment]
@vtrykoz  середина 2018-го уже.

**Comment by vtrykoz** [comment]
@Globik и не говори

**Comment by luisvallejomohl** [comment]
``` javascript
if(location.hash = '#_=_'){
var uglyURL = location.href;
var cleanURL = uglyURL.split('#')[0];
location.href = cleanURL;
};
``` is the answer

**Comment by ashnamuh** [comment]
It's my answer

https://github.com/ashnamuh/rm-facebook-passport-redirect-hash

**Comment by Reg0804** [comment]
На дворе начало 2019, до сих пор не исправили баг! 😱

**Comment by b1acksun** [comment]
Март 2020, до сих пор не исправили баг!

**Comment by vtrykoz** [comment]
Еще пару годиков и багу исполнится десятилетие

**Comment by TokerX** [comment]
> The answer is:
> 
> ```js
> if(location.hash = '#_=_'){
> location.href = location.href.split('#')[0];
> }; 
> ```

Haha, no it's not. This will put you in an infinite loop. ;)
It should be if(location.hash === '#_=_'){

**Comment by dhdkhoa** [comment]
Март 2021, до сих пор не исправили баг!

**Comment by mopkoff** [comment]
Привет из 2023
