### ISSUE TITLE
Extend the the user creation and login process

### ISSUE THREAD

**Issue by mikesparr** [jaredhanson/passport-facebook#123]
## Issue 1: remoteHook event on User.create fails after adding Passport
When adding passport does it override the built-in User model for Loopback and somehow block events from registering for remote hooks?

## Issue 2: Passport login does not create Loopback accessToken
Is there a way to extend the passport login for all strategies to add logic to also call Loopback's `User.login()`.  Their function returns the `accessToken` which would be used for subsequent requests and leverage their ACL and RBAC.

----

Testing out Loopback and https://github.com/strongloop/loopback-example-passport and they have concept of "remote hooks" and "operation hooks".  In their system when a `User` is created, you can attach a hook to the `create` and add custom logic like emailing a verification link.

After integrating Passport into Loopback in their example application, and using a local strategy for passport, it appears the `create` is not recognized as remote hook event so I cannot extend that with a remote hook like the following.

`user.js` (model config)
~~~
var path = require('path');
var app = require(path.resolve(__dirname, '../../server/server'));

module.exports = function(user) {
  //send verification email after registration
  user.afterRemote('create', function(context, user, next) {
    console.log('> user.afterRemote triggered');

    var options = {
      type: 'email',
      to: user.email,
      from: 'noreply@myco.com',
      subject: 'Thanks for registering.',
      template: path.resolve(__dirname, '../../server/views/pages/verify.jade'),
      redirect: 'pages/verified',
      user: user
    };

    user.verify(options, function(err, response) {
      if (err) {
        next(err);
        return;
      }

      console.log('> verification email sent:', response);

      context.res.render('pages/response', {
        title: 'Signed up successfully',
        content: 'Please check your email and click on the verification link '
          + 'before logging in.',
        redirectTo: '/',
        redirectToLinkText: 'Log in'
      });
    });
  });

  //send password reset link when requested
  user.on('resetPasswordRequest', function(info) {
    var url = 'http://' + app.get('email_link_domain') + '/reset-password';
    var html = 'Click <a href="' + url + '?access_token=' + info.accessToken.id
      + '">here</a> to reset your password';

    user.app.models.Email.send({
      to: info.email,
      from: info.email,
      subject: 'Password reset',
      html: html
    }, function(err) {
      if (err) return console.log('> error sending password reset email');
      console.log('> sending password reset email to:', info.email);
    });
  });
};
~~~

`routes.js` (custom routes)
~~~
    router.post('/signup', function (req, res, next) {

      var newUser = {};
      newUser.email = req.body.email.toLowerCase();
      newUser.username = req.body.username.trim();
      newUser.password = req.body.password;

      User.create(newUser, function (err, user) {
        if (err) {
          req.flash('error', err.message);
          return res.redirect('back');
        } else {
          // Passport exposes a login() function on req (also aliased as logIn())
          // that can be used to establish a login session. This function is
          // primarily used when users sign up, during which req.login() can
          // be invoked to log in the newly registered user.
          req.login(user, function (err) {
            if (err) {
              req.flash('error', err.message);
              return res.redirect('back');
            }
            console.log('Logged user in using Passport req.login()');
            console.log(req.user);
            return res.redirect('/auth/account');
          });
        }
      });
    });
~~~

It's unclear why the `create` is not registering the remote hook.  In other tests without Passport integration, it works, so I'm guessing something happens once Passport added to the User model in Loopback.  

I appreciate any insights or ideas why this might be occurring or if you've heard adding Passport to Loopback whether it eliminates some events from being recognized.

**Comment by LuisMejiaF** [comment]
Hello, I'm trying to solve the same problem. I need send a verification email, just like you.

Have you found any solution or alternative to this? Thank you.

**Comment by devrajput15** [comment]
Have you been able to solve the issue? I am having similar issue.

**Comment by jaredhanson** [comment]
LoopBack is a higher-level framework that builds on Passport core.  Any such integration is outside the scope of this project.  Please file this issue with the relevant project.

**Comment by LuisMejiaF** [comment]
@jaredhanson But what if I really want to integrate passportjs and remote hooks over Passport actions? I mean, Loopback should have something to fire "manually" remote hook events that I want.

**Comment by jaredhanson** [comment]
This project has nothing to do with Loopback or remote hooks.  If you really want to do that, you need to make that happen at a higher level.  I don't have any particular guidance or recommendations on that topic.

**Comment by mikesparr** [comment]
https://github.com/strongloop/loopback Try here

**Comment by mikesparr** [comment]
Or better here https://github.com/strongloop/loopback-component-passport

**Comment by mikesparr** [comment]
Jared the original question is about whether you can extend passport login to call another function. 

Loopback for example needs a User.login() to initialize token for subsequent requests.

**Comment by LuisMejiaF** [comment]
@jaredhanson my issue is similar to what @mikesparr asked in the first comment of this "issue": I can integrate easily passport-facebook component in my Loopback project. It works as expected, it authenticates users with their facebook account. The problem comes that, if use this component, we loose two important features of Loopback: Remote Hooks and the ability to get the accessToken that Loopback creates.

I'm not sure about @mikesparr , but my request for you could be: Can you please add a remote hook for the user create and login for this component and also when the user log in successfully with facebook return the accessToken from Loopback?

Thanks.

**Comment by jaredhanson** [comment]
I don't know enough about Loopback to understand what a remote hook is or what sort of facilities are required.

If you want to take a stab at implementing such things, please do and submit a PR for review.  I have no interest implementing such things myself.
