### ISSUE TITLE
Facebook API 2.4 with passport-facebook doesn't provide data 

### ISSUE THREAD

**Issue by isotnikov** [jaredhanson/passport-facebook#126]
I can't get almost all data except DisplayName. With API 2.3 all worked fine. Look at the screenshot please. passport-facebook version is latest. 

![2015-07-14 21-20-31](https://cloud.githubusercontent.com/assets/2997451/8683645/d41066c2-2a7c-11e5-96d8-8f6ac2a2b010.png)

**Comment by isotnikov** [comment]
Also note that 2.2 is expired
![2015-07-14 23-19-43 facebook marketing api changelog](https://cloud.githubusercontent.com/assets/2997451/8684206/c6ca0fe2-2a7f-11e5-93a4-fcb289a41b4b.png)

**Comment by mzalazar** [comment]
God damn facebook hehe

**Comment by mzalazar** [comment]
OK, I GOT IT!
It needs a param "profileFields" to be set, like this:

    passport.use(new FacebookStrategy({
      clientID: FACEBOOK_APP_ID,
      clientSecret: FACEBOOK_APP_SECRET,
      callbackURL: "http://localhost:3000/auth/facebook/callback",
      profileFields: ['id', 'birthday', 'email', 'first_name', 'gender', 'last_name']
        ....

I hope this will be useful to you! ;-)

**Comment by isotnikov** [comment]
@mzalazar oh, thank you very much!

**Comment by mitkodkn** [comment]
So is the usage of the scope array even needed?

**Comment by VincentPuget** [comment]
Thank you !!

**Comment by ekryski** [comment]
@jaredhanson you can probably close this as it's now documented in the README.
