### ISSUE TITLE
Add the 'state' query parameter to the authenticate call

### ISSUE THREAD

**Issue by arius25** [jaredhanson/passport-facebook#14]
Please add the 'state' parameter to the authenticate call for the strategies which support it (e.g. Facebook) as per 
https://developers.facebook.com/docs/authentication/server-side/

Thanks,
 Marius

**Comment by wzup** [comment]
It is not documented, isn't it?
There is no any `state` word in a whole [README.md](https://github.com/jaredhanson/passport-facebook). 

1 . Why? Does it work whatsoever? 
2. Where can I read **ALL** parameters that may be passed to strategy config? In one place, please. Now I have to search them all over the internet, one by one. `passReqToCallback` isn't mentioned in README.md as well. Now `state`. I'm curious how many good options are hidden? not documented properly.

**Comment by konstardiy** [comment]
Is string state supports still?
My scenario is to pass some encoded JSON to /auth/facebook/callback with these extra parameters.
I need to avoid usage of session.

**Comment by veeramarni** [comment]
any luck with custom `state` string?

**Comment by CLClark** [comment]
Passing "state: true" causes the Strategy object, upon instantiation, to write itself a "_stateStore" property with the value coming from ('passport-oauth2/state/session').SessionStore. Look up that module to see how the "state" field is handled...  There does not appear to be a way to modify the state constructor without editing the SessionStore code. SessionStore is referred to as SessionStateStore in the passport-oauth2 constructor (from which passport-facebook strategy inherits).

**Comment by jayarjo** [comment]
I receive:

> OAuth 2.0 authentication requires session support when using state. Did you forget to use express-session middleware

It's and API host so I'm not using sessions, am I obligated to? Can I switch this requirement off @jaredhanson, since I'm validating state manually in a different way?

**Comment by www-chique** [comment]
> 
> 
> Is string state supports still?
> My scenario is to pass some encoded JSON to /auth/facebook/callback with these extra parameters.
> I need to avoid usage of session.

I had the very same situation.
However, I found a workaround
```
passport.authenticate("facebook", { scope: ["email"], state: "FOOBAR" }, async (err, user, info)=> {
     console.log(req.query.state); //Receives here "FOOBAR"
})(req, res);
```
And
```
passport.use(
	"facebook",
	new FacebookStrategy(
		{
			clientID: ...,
			clientSecret: ...,
			callbackURL: ...,
			profileFields: ...,
			passReqToCallback: true,
		},
		async (req: Request, accessToken: string, refreshToken: string, profile: any, done: any) => {
				console.log("state: " + req.query.state); //Works here too "FOOBAR"
		}
	)
);
```
So, instead of "FOOBAR", you can pass json string as well.

**Comment by jaredhanson** [comment]
For those who stumble upon this issue looking for how to handle state in OAuth 2.0, `passport-oauth2@1.6.0` adds support for automatically persisting application-level state.   More information is available on the blog: [Application State in OAuth 2.0](https://medium.com/passportjs/application-state-in-oauth-2-0-1d94379164e)
