### ISSUE TITLE
Email field is missing from the profile field. 

### ISSUE THREAD

**Issue by SarasArya** [jaredhanson/passport-facebook#143]
I am using facebook's graph API v2.5 and after seeing the issues open here and applying there I am posting here. For some people 
`profileFields: ["id", "birthday","first_name","email", "last_name", "gender", "picture.width(200).height(200)"]`
this worked. For some 
`profileFields: ["id", "birthday","first_name","emails", "last_name", "gender", "picture.width(200).height(200)"]` this worked.
Fortunately for me neither is working... 
has something changed in v2.5 I mean all of the mentioned people solution is working in 2.4 supposedly But aren't working for me. 

My code

 ` app.get('/mobile/auth/login/facebook', passport.authenticate('facebook', { scope: 'email' }));`

    passport.use('facebook', new FacebookStrategy({
    	clientID: config.facebookAuth.clientID,
    	clientSecret: config.facebookAuth.clientSecret,
    	callbackURL: config.facebookAuth.callbackURL,
    	profileFields: ["id", "birthday","first_name","email", "last_name", "gender", "picture.width(200).height(200)"],
        passReqToCallback: true
  		},function(req, accessToken, refreshToken, profile, done) {
			process.nextTick(function() {
				console.log(profile._json);
				console.log(profile.emails);
     });
     }));

I don't see anything here .
The reply I am getting here. 

    { id: '10208549480080473',
      first_name: 'Saras',
      last_name: 'Arya',
      gender: 'male',
      picture: 
        { data: 
          { height: 200,
            is_silhouette: false,
             url: 'https://scontent.xx.fbcdn.net/hprofile-xpf1/v/t1.0-     1/p200x200/12004684_10208423439289532_8512110980327477128_n.jpg?oh=88876a89d4dfd544e2943ad1672a533a&oe=56AC7B59',
        width: 200 } } }
     undefined
without the email field. What is wrong?

**Comment by palmdeezy** [comment]
+1

**Comment by live13** [comment]
you need change 'email' to 'emails'
profileFields:["emails"]
and in reply you recive array emails with user email in element 0.

**Comment by LeandroFavero** [comment]
I'm trying:     profileFields: ['id', 'displayName','gender','emails','birthday','location']

But emails, birthday and location don't return.

**Comment by arxpoetica** [comment]
This isn't working for me either. Neither `email` or `emails` is working.

**Comment by SarasArya** [comment]
Hey @arxpoetica  can you to facebook.com and check if your email id is verified and post  a screenshot here. That would be of lot of help.

**Comment by arxpoetica** [comment]
Forgot to come back here, but figured out the problem. I needed to set the scope property on the authenticate call:

```js
app.get('/auth/facebook', passport.authenticate('facebook', {
	scope: ['public_profile', 'email', ...],
}));
```

That fixed it.

**Comment by SarasArya** [comment]
Nice I am closing this issue for now. If anyone feels any clarification is needed. Will log a new issue. Thanks folks...
