### ISSUE TITLE
A fail-safe Passport-Facebook solution?

### ISSUE THREAD

**Issue by emorling** [jaredhanson/passport-facebook#145]
I was hoping that Passport-Facebook would be a drop-in solution. However, there appears to be many caveats with the Facebook API. Specifically "This authorization code has expired." and retrieving a long-living token. Is there a wrapper that handles all the knick-knacks of FB? Or is each developer re-inventing the wheel? :)

**Comment by emorling** [comment]
And includes FB.getLoginStatus and acts appropriately.

**Comment by jaredhanson** [comment]
Passport is about authentication only.  It's not intended to be some high-level wrapper, so such features are out-of-scope of this project.
