### ISSUE TITLE
Check which extra permissions have been rejected, and reask them

### ISSUE THREAD

**Issue by kikar** [jaredhanson/passport-facebook#148]
According to [Facebook API](https://developers.facebook.com/docs/facebook-login/handling-declined-permissions) you can check permissions rejected with `GET /me/permissions`.
Would be nice for the scope to be an array of objects of type `{ required: true, value: 'email'}` to let the developer specify which permissions are fundamental for his app.

Once requested the permissions, to make a check that the required ones are fullfilled, and in the case they're not to rerequest them immediately.

**Comment by jaredhanson** [comment]
Do this at a higher level in your application if you need it.  Passport is about authentication only.
