### ISSUE TITLE
In 2.1 default profile fields returned after login are changed

### ISSUE THREAD

**Issue by mettjus** [jaredhanson/passport-facebook#150]
Moving from 2.0.x to 2.1 (Facebook API from 2.2 to 2.5) default profile fields returned at login are changed. With Facebook API 2.5 only `id` and `name` fields are returned. I think users should be made aware of this as for example in our case we didn't get the default profile fields we were getting before, in particular the `email` field.

**Comment by jaredhanson** [comment]
If needed, you can change the version by setting the `profileURL` option:

```
profileURL: https://graph.facebook.com/v2.2/me
```

This strategy just tracks the latest version of the Facebook SDK.  It's not my intention to repeat what Facebook says, so people using this strategy should make sure they track any changes in the upstream API.
