### ISSUE TITLE
successRedirect vs callbackURL

### ISSUE THREAD

**Issue by georgi-kovachev** [jaredhanson/passport-facebook#151]
When I use passport-facebook . I do like this for configuration.

passport.use(new FacebookStrategy({
  clientID: config.facebook.facebook_app_id,
        clientSecret: config.facebook.facebook_secret_id,
        callbackURL: config.facebook.callback_url,
        passReqToCallback: true
    },
      function(req, accessToken, refreshToken, profile, done) {
     //code for success: Function A
    }

And then to authenticate

passport.authenticate('facebook', {
        successRedirect: 'http://app.mykomae.com/#/app/dashboard',
        failureRedirect: '/auth/unauthorized'
    }));

what is difference between successRedirect vs callbackURL?

And when the function handler 'Function A: above code' is calling?

Thanks

**Comment by jaredhanson** [comment]
All your questions are answered in the [documentation](http://passportjs.org/docs).
