### ISSUE TITLE
findOrCreate is not a function

### ISSUE THREAD

**Issue by villander** [jaredhanson/passport-facebook#152]
I using passport-facebook version 2.1.0

```
function(accessToken, refreshToken, profile, done) {
        User.findOrCreate({ facebookId: profile.id }, function(err, user) {
          if (err) { return done(err); }
          done(null, user);
        });
      }));
```

TypeError: User.findOrCreate is not a function
   at Strategy._verify (/Users/flama/Projects/analytics-app/config/passport.js:86:14)
   at /Users/flama/Projects/analytics-app/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:190:24
   at /Users/flama/Projects/analytics-app/node_modules/passport-facebook/lib/strategy.js:181:5
   at passBackControl (/Users/flama/Projects/analytics-app/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:125:9)
   at IncomingMessage.<anonymous> (/Users/flama/Projects/analytics-app/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:72:20)
   at IncomingMessage.emit (events.js:166:7)
   at endReadableNT (_stream_readable.js:893:12)
   at doNTCallback2 (node.js:429:9)
   at process._tickCallback (node.js:343:17)

**Comment by jaredhanson** [comment]
`User.findOrCreate` is something implemented by your application, and is not related to Passport.  Double check that you are `require`ing the appropriate modules.

**Comment by Arcrammer** [comment]
What would those be? Which modules?

**Comment by mpumiJavaDev** [comment]
Hi @villander did you manage to find the solution for this? On my side Im indeed requiring the appropriate modules but Im still getting the error. Here's my code:

User.js -----> Router class



/**
 * Created by Phumelele on 2017-02-14.
 */
var express = require('express');
var bodyParser = require('body-parser');
var urlencodedParser = bodyParser.urlencoded({ extended: false });
var router  = express.Router();
var User = require('../models/user');
var passport = require('passport');
var LocalStrategy = require('passport-local').Strategy;


//p Register
router.get('/register', function (req, res) {
    res.render('register')
});

//p Login
router.get('/login', function (req, res) {
    res.render('login')
});

//p Register Users
router.post('/register', urlencodedParser, function (req, res) {
    var name = req.body.name;
    var username = req.body.username;
    var email = req.body.email;
    var password = req.body.password;
    var password2 = req.body.password2;

    //p Validation
    req.checkBody('name', 'Name is required').notEmpty();
    req.checkBody('email', 'Email is required').notEmpty();
    req.checkBody('email', 'Please enter a valid email').isEmail();
    req.checkBody('username', 'Username is required').notEmpty();
    req.checkBody('password', 'Password is required').notEmpty();
    req.checkBody('password2', 'Password confirmation does not match').equals(password);

    var errors = req.validationErrors();
    if(errors){
       //p If errors re render the form and show the errors.
        res.render('register',{
           errors:errors
        });
    }else{
        //p This is where we are inserting the user on Registration using the model
        var newUser = new User({
            name: name,
            email: email,
            username: username,
            password: password
        });

        User.createUser(newUser, function (err, user) {
            if(err) throw err;
            console.log(user);
        });

        //p Set success message
        req.flash('success_msg', 'You are now registered and can now login');

        //p Redirect after registration
        res.redirect('/users/login');
    }

});
    // this basically gets the user name, compares it to the username entered and does the same with the password
     passport.use(new LocalStrategy(function (username, password, done) {
         console.log('username before calling UserByUsername: ' + username)
         console.log('password before calling UserByUsername: ' + password)
        User.getUserByUsername(username, function (err, user) {
            console.log('password before calling UserByUsername: ' + password)
            if(err) throw err;
                if(!user){
                return done(null, false, {message: 'Unknown User'});
           }

            User.comparePassword(password, user.password, function (err, isMatch) {
                if(err) throw err;
                if(isMatch){
                    return done(null, user);
                }else{
                    return done(null, false, {message: 'Invalid Password'});
                }
            });

        });

    }));

passport.serializeUser(function(user, done){
    done(null, user.id);
});

passport.deserializeUser(function (id, done) {
    User.getUserById(id, function (err, user) {
        done(err, user);
    });
});

//p Using passport to login our users
//p Making a post request to '/login'
    router.post('/login',
        //p using local strategy as we are using a local database
        passport.authenticate('local', {
            successRedirect: '/',
            failureRedirect: '/users/login',
            failureFlash: 'Invalid username or password'}),

           function (res, req) {
               console.log('Authentication Successful');
            //p Redirect to the dashboard
               req.flash('success', 'You are logged in');
               res.redirect('/');
           }
    );


module.exports = router;


My Model Class where I have defined the method "getUserByUsername"

/**
 * Created by Phumelele on 2017-02-14.
 */
var mongoose  = require('mongoose');
var bcrypt = require('bcryptjs');


//User Schema

var UserSchema = mongoose.Schema({
    username: {
        type: String,
        index: true
    },

    password: {
        type: String
    },

    email: {
        type: String
    },

    name: {
        type: String
    }
});


//p Create Users
    module.exports.createUser = function (newUser, callback) {
        //p Hash password using bcrypt
        var bcrypt = require('bcryptjs');
        bcrypt.genSalt(10, function(err, salt) {
            bcrypt.hash(newUser.password, salt, function(err, hash) {
                // Store hash in your password DB.
                newUser.password = hash;
                newUser.save(callback);
            });
        });

    //Get user by username function
        module.exports.getUserByUsername = function (username, callback) {
        console.log('UserByUsername');
        var query = {username: username};
        user.findOne(query, function (err, user) {
            console.log(user.username);
            callback(err, user);
        });
    }

    module.exports.getUserById = function (id, callback) {
        user.findById(id, callback);
    }

    module.exports.comparePassword = function (candidatePassword, hash, callback) {
        bcrypt.compare(candidatePassword, hash, function (err, isMatch) {
            if(err) throw err;
            callback(null, isMatch);
        });
    }
}

//p Variable that can access outside of this file
var User = module.exports = mongoose.model('User', UserSchema);

however I am still getting this error:
TypeError: User.getUserByUsername is not a function
    at Strategy._verifyTypeError: User.getUserByUsername is not a function
    at Strategy._verify (C:\Projects\LoginApp\routes\users.js:71:14)

**Comment by jamesalbert** [comment]
@mpumiJavaDev bruh...

**Comment by Ankita2002-Fr** [comment]
Use mongoose findOrCreate plugin. 
https://www.npmjs.com/package/mongoose-findorcreate
