### ISSUE TITLE
Duplicating first_name & second_name

### ISSUE THREAD

**Issue by RohovDmytro** [jaredhanson/passport-facebook#154]
I want to set profileFields manually: 

`
profileFields: [
"email",
            "gender",
            "link",
            "locale",
            "first_name",
            "last_name",
            "name",
            "name_format",
            "timezone",
            "is_verified",
            "verified",
            "permissions",
            "cover",
            "devices",
            "id"
]
`

But when this list includes first_name and last_name facebook generates an error.

> "Syntax error \"Field last_name specified more than once. This is only possible before version 2.1\" at character 55: email,gender,link,locale,first_name,last_name,last_name,first_name,middle_name,name_format,timezone,is_verified,verified,permissions,cover,devices,id"

**Comment by pirxpilot** [comment]
`'name'` [is translated][1] by `passport-facebook` to `'last_name', 'first_name', 'middle_name'`
Skip those three (or skip `name`) in your list and it'll start working.

[1]: https://github.com/jaredhanson/passport-facebook/blob/master/lib/strategy.js#L213
