### ISSUE TITLE
passport.authenticate hangs 

### ISSUE THREAD

**Issue by Tom2277** [jaredhanson/passport-facebook#160]
The Facebook , Twitter and local strategies all work on my local computer but Facebook hangs on my production server.  Any help about where to turn would be appreciated.  

I've experimented for days, reading docs and past issues and SO and trying everything but I've been able to determine that the callback does get called with the information needed (it's not a secret key issue etc) but that something seems to go awry AFTER I've tried to call passport.authenticate in the callback route with the needed information present in the request.

The Local strategy works fine deployed at AWS but the Facebook and Twitter authentications hang.  Sticking to Facebook here is a glimpse of a server log:

GET /auth/facebook 302 1ms - 0b

GET /auth/facebook/callback?code=AQA3gfVchdkMq_Ui2wy7vL6SHfzXHTQZGmlf7dDHu9FxAWcewBi-7_ihILbZ3vyRpXLPV0BtyXJFyvXb0Q2YOPvCRewMyw9Dun3TW3l6QIWA5kT8BnZVw93GObgszOIQARvgmF18CTuCdaHSu0SeUqALTEREDqSNGkJj5bPQqOocMV3dK8OAXzPBsl3Xmijl_e5IGjKd9N4uzCgc4SXInOAKsOqDgcqh5qQgu28Cp25PC5wXKG9EMab3lqMflJet1O0u7IN9TaJH5E6veum47QEvTx3p9tuufYwcp4mOcP9 200 119811ms

GET /auth/facebook 302 1ms - 0b

InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/home/ubuntu/www/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:370:17)
    at /home/ubuntu/www/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /home/ubuntu/www/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
    at ClientRequest.<anonymous> (/home/ubuntu/www/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:148:5)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)`

Again .. thanks for any tips about how to go about debugging the issues.
There was one issue #116 that might have been having the same issue but I didn't understand how that was solved (network issue?) and I'm not having issues connecting

**Comment by Tom2277** [comment]
Solution: abandoned my existing EC2 launch and creating a new EC2 launch.  Still have no idea what actually went wrong.

Description of my circumstances at : https://github.com/angular-fullstack/generator-angular-fullstack/issues/1834#issuecomment-218517979

**Comment by senseluo** [comment]
same here, i was again and again ran into this in my local dev environment (mac OS). so did you mean that you get resolved by deploying to a new ec2 instance without changing anything?

thanks!

thanks!

**Comment by Tom2277** [comment]
@senseluo Sorry for the delayed response.  I do not remember making any other changes beyond creating a new EC2 instance .  I had tried to wipe the existing EC2 instance but that did not work. Somehow something remained on the instance even though I thought I was redoing the entire image.
