### ISSUE TITLE
What scope/profileFields necessary to get username in profile?

### ISSUE THREAD

**Issue by olalonde** [jaredhanson/passport-facebook#169]
What scope or profileFields do I need to specify in order to get the username property set on the profile object?

**Comment by alexgalin** [comment]
Same here, I get this:
name: 'undefined undefined'

**Comment by mbrand1** [comment]
I don't think this is available anymore.  This is the Facebook error I get:

FacebookGraphAPIError: (#12) username field is deprecated for versions v2.0 and higher

**Comment by olalonde** [comment]
Ah, strange. Is there no way at all to get the user's facebook profile URL or something :/ ?

**Comment by alexgalin** [comment]
I ended up using [fbgraph](https://www.npmjs.com/package/fbgraph) 

var graph = require('fbgraph');  

graph.setAccessToken(user.facebook.token);       
graph.get(user.facebook.id ',         
    function(err, result){                             
        if(err) {                                    
          throw err;
        }                                            
          return result.name;                                                                                  
    });

**Comment by mbrand1** [comment]
Oh, I saw 'username' so that threw me.  You can ask for 'name' or 'profileUrl'.  This is my profileFields arg:

profileFields   : ['id', 'photos', 'name', 'displayName', 'gender', 'profileUrl', 'email'],

**Comment by olalonde** [comment]
@alexgalin @mbrand1 Thanks. I guess I could get the username from `profileUrl` somehow.

**Comment by Coyas** [comment]
how can i get this fields, the undefined fields:
{ id: '24864596',
  username: undefined,
  displayName: undefined,
  name:
   { familyName: undefined,
     givenName: undefined,
     middleName: undefined },
  gender: undefined,
  profileUrl: undefined,
  emails: [ { value: 'adidas.coyas@hotmail.com' } ],
  provider: 'facebook',
  _raw:
   '{"email":"","id":""}',
  _json:
   { email: 'ad.com', id: '24520596' } }
