### ISSUE TITLE
profile.id undefined

### ISSUE THREAD

**Issue by Acesonnall** [jaredhanson/passport-facebook#185]
Hello,

So I've attempted to fix this issue for hours but to no avail. The error says: 

![image](https://cloud.githubusercontent.com/assets/11043749/19957541/9904434e-a165-11e6-8645-f9140bd4ad46.png)

And upon running in debug mode (That's also what the "profile undefined" was -- a console log):
![image](https://cloud.githubusercontent.com/assets/11043749/19957622/329f3248-a166-11e6-8bd3-d83a3064fe38.png)

After doing hours of research, I can't seem to figure out what the profile field is not being sent back.

Here's my passport.js:
`passport.use('facebook', new FacebookStrategy({
            clientID        : configAuth.facebookAuth.clientID,
            clientSecret    : configAuth.facebookAuth.clientSecret,
            callbackURL     : configAuth.facebookAuth.callbackURL,
            passReqToCallback : true,
            profileFields: ['id', 'emails', 'name']
        },

        // facebook will send back the token and profile
        function(accessToken, refreshToken, profile, done) {

            console.log('profile', profile);

            // asynchronous
            process.nextTick(function() {

                // find the user in the database based on their facebook id
                User.findOne({ 'id' : profile.id }, function (err, user) {

                    // if there is an error, stop everything and return that
                    // ie an error connecting to the database
                    if (err)
                        return done(err);

                    // if the user is found, then log them in
                    if (user) {
                        return done(null, user); // user found, return that user
                    } else {
                        // if there is no user found with that facebook id, create them
                        var newUser            = new User();

                        // set all of the facebook information in our user model
                        newUser.facebook.id    = profile.id; // set the users facebook id
                        newUser.facebook.id    = accessToken; // we will save the token that facebook provides to the user
                        newUser.facebook.name  = profile.name.givenName + ' ' + profile.name.familyName; // look at the passport user profile to see how names are returned
                        newUser.facebook.email = profile.emails[0].value; // facebook can return multiple emails so we'll take the first

                        // save our user to the database
                        newUser.save(function(err) {
                            if (err)
                                throw err;

                            // if successful, return the new user
                            return done(null, newUser);
                        });
                    }

                });
            });

        }));`
And my routes
`/ route for facebook authentication and login
    app.get('/auth/facebook', passport.authenticate('facebook', { scope : ['email', 'public_profile'] }));

    // handle the callback after facebook has authenticated the user
    app.get('/auth/facebook/callback',
        passport.authenticate('facebook', {
            successRedirect : '/profile',
            failureRedirect : '/'
        }));`

**Comment by Acesonnall** [comment]
Problem solved after buckling down and debugging the entire passport facebook strategy.

Right here in strategy.js is where things matter.
![image](https://cloud.githubusercontent.com/assets/11043749/19959598/fcdd92fc-a175-11e6-9624-ac794fbe2953.png)

The strategy checks to see what the length of the arguments you are passing in is, which can be affected by the passReqToCallBack parameter. I had accidentally set this would adding the corresponding 'req' parameter needed, so my data was shifted (profile was stored in "done" which means verification was eliminated).

Good stuff.

**Comment by libnine** [comment]
Can you specify about where you placed the req parameter? I'm having an issue with this exact problem as well.

**Comment by Acesonnall** [comment]
No problem, so based on the image above, we see that the middleware is checking if 'self._passReqToCallback' is true. If it is, it will validate the arguments with the 'req' parameter first.

So when you want to pass the req parameter to the callback, you should set up your function as such:
```
 passport.use('facebook', new FacebookStrategy({
            clientID: [YOUR CLIENT ID]
            clientSecret: [YOUR CLIENT SECRET],
            callbackURL: [YOUR CALLBACK URL],
            profileFields: [YOUR FIELDS],
            passReqToCallback: true
        },

        // facebook will send back the token and profile
        (req, accessToken, refreshToken, profile, done) => {
        
        }));
```

**Comment by libnine** [comment]
Hmm.. so the login works, but the following fields populate under my facebook params:

email: 
name: undefined undefined

here's my code:

 // facebook
    passport.use(new FacebookStrategy({
        clientID: configAuth.facebookAuth.clientID,
        clientSecret: configAuth.facebookAuth.clientSecret,
        callbackURL: configAuth.facebookAuth.callbackURL,
        passReqToCallback: true
    },
    function(req, token, refreshToken, profile, done) {
        process.nextTick(function() {
            if (!req.user) {
                User.findOne({ 'facebook.id' : profile.id }, function(err, user) {
                    if (err)
                        return done(err);
                    if (user) {
                        if (!user.facebook.token) {
                            user.facebook.token = token;
                            user.facebook.name  = profile.name.givenName + ' ' + profile.name.familyName;
                            user.facebook.email = profile.email;

                            user.save(function(err) {
                                if (err)
                                    throw err;
                                return done(null, user);
                            });
                        }

                        return done(null, user); // user found, return that user
                    } else {
                        var newUser            = new User();

                        newUser.facebook.id    = profile.id;
                        newUser.facebook.token = token;
                        newUser.facebook.name  = profile.name.givenName + ' ' + profile.name.familyName;
                        newUser.facebook.email = profile.email;

                        newUser.save(function(err) {
                            if (err)
                                throw err;
                            return done(null, newUser);
                        });
                    }
                });

            } else {
                var user            = req.user;

                user.facebook.id    = profile.id;
                user.facebook.token = token;
                user.facebook.name  = profile.name.givenName + ' ' + profile.name.familyName;
                user.facebook.email = profile.email;

                user.save(function(err) {
                    if (err)
                        throw err;
                    return done(null, user);
                });
            }
        });
    }));
  
  app.get('/auth/facebook', passport.authenticate('facebook', { scope : 'email' }));

        // handle the callback after facebook has authenticated the user
        app.get('/auth/facebook/callback',
            passport.authenticate('facebook', {
                successRedirect : '/profile',
                failureRedirect : '/'
            }));

Not sure what i'm doing wrong..

**Comment by omererbil** [comment]
to avoid return undefined from name field just change your code for this : 
user.facebook.name = profile.displayName
