### ISSUE TITLE
Semi-Dynamic callbackUrl

### ISSUE THREAD

**Issue by ghost** [jaredhanson/passport-facebook#2]
Currently it does not seem possible to use a 'semi-dynamic' callbackUrl.  In the examples, one specifies a static callbackUrl = 'http://localhost/auth/facebook/callback', which isn't very useful for when you want to remember where authentication has taken place.

 For instance, if the user clicks on a Login link on /page/1/2/3 then he/she would expect to be returned to the /page/1/2/3 upon authentication.  When creating the params for the callbackUrl, passport should check for an optional passed GET parameter called 'next' and encode it into the callbackUrl.  The 'semi-dynamic' callbackUrl would then be  'http://localhost/auth/facebook/callback?next=/page/1/2/3'  

The logic in /auth/facebook/callback would then be able to get the next parameter and perform the appropriate action to take the user back to /page/1/2/3

**Comment by kitlee** [comment]
Is it really possible to dynamically set the callbackUrl?
Should the callbackUrl match the settings of the client in the OAuth2 service provider?

**Comment by thor84no** [comment]
@kitlee Even if that's true you still might have multiple possible callback urls. Our server for example can be reached through different host names and will behave slightly differently (branding basically) based on that host name. The callback URL must therefore match the hostname of the original request.

**Comment by yorkie** [comment]
An example router to show why I need this feature: `/auth/:provider/callback`, or we should define them one by one.

**Comment by shanehsu** [comment]
@yaiza-bailen I've looked at your code, and I've tried to do something similar like this,

    // Setting Up PassportJS to use Facebook Strategy
    passport.use(new FacebookStrategy({
        clientID: app.locals.facebookClientID,
        clientSecret: app.locals.facebookClientSecret,
        // callbackURL: 'http://' + app.locals.hostname + ':' + app.locals.port + '/api/beta/auth/facebook/callback/'
    }, function(accessToken, refreshToken, profile, done) {
        var facebookID = profile.id;
        var displayName = profile.displayName;
        done(null, {});
        // TODO: call the done(err, user) handler with either done(err, null) or done(null, user)
        }
    ));
    
    // /api/beta/auth/facebook, this redirects user to a Facebook page
    router.get('/facebook', function(req, res, next) {
            console.log('callback url = ', 'http://' + app.locals.hostname + ':' + app.locals.port + '/api/beta/auth/facebook/callback?client=' + req.query.callback)
            passport.authenticate('facebook', {
                session: false,
                callbackURL: 'http://' + app.locals.hostname + ':' + app.locals.port + '/api/beta/auth/facebook/callback/123'
            })(req, res, next);
        }
    );
    
    // This will handle the callback from Facebook, and redirect user to another URL while handing out a Token
    router.get('/facebook/callback/:id', passport.authenticate('facebook', {session: false}), function(req, res) {
        res.send('DONE!');
    });

This sadly does not work, I was given this error

    [FacebookTokenError: Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request]

Anything I missed?

**Comment by christinedraper** [comment]
@shanehsu Try passing the callbackURL on both calls to passport.authenticate. I had a similar situation with Amazon, and this fixed it.

**Comment by raosushant** [comment]
Wanted to share since I was stuck on this for a while. I wanted to use a query string since the solution posted above uses separate routes for every callback. 

```
router
  .get('/', passport.authenticate('facebook', {
    scope: ['email', 'user_about_me'],
    callbackURL: '/auth/facebook/callback?myQuery=' + req.query.myQuery,
    failureRedirect: '/signup',
    session: false
  }))

router.get('/callback', function(req, res, next) {
  passport.authenticate(
    'facebook', {
      callbackURL: '/auth/facebook/callback?myQuery=' + req.query.myQuery,
      failureRedirect: '/signup',
      session: false
  })(req, res, next);
}, setTokenCookie);
```

In `setTokenCookie(req, res)` you can redirect to the desired location 

`res.redirect('/'+req.query.myQuery);`

**Comment by sriram-bhargav** [comment]
@shanehsu: Did @christinedraper  suggestion work? I tried using same dynamic callbackURL in both calls. I seem to get same error from facebook: "Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request"

Here is my code for those two calls:
passport.use(new FacebookStrategy({
        clientID        : APP_ID,
        clientSecret    : APP_SECRET,
        enableProof     : true,
        passReqToCallback: true,
        profileFields   : ['id', 'email', 'gender', 'link', 'name'],
        callbackURL     : AUTH_CALLBACK_URL,
    }, function (request, accessToken, refreshToken, profile, done) {
        console.log('PROFILE: ', profile);
        done(null, profile);
    }
));

app.get('/auth/facebook', (req, res, next) => {
    passport.authenticate('facebook', {
        callbackURL: AUTH_CALLBACK_URL + '?' + 'redirect_uri=' + req.query.redirect_uri,
        scope: ['email'],
    })(req, res, next);
});

app.get('/auth/facebook/callback', (req, res, next) => {
    passport.authenticate('facebook', {
        callbackURL: AUTH_CALLBACK_URL + '?' + 'redirect_uri=' + req.query.redirect_uri,
        scope: ['email'],
        failureRedirect: '/',
        successRedirect: '/'
    })(req, res, next);
});

**Comment by sriram-bhargav** [comment]
@jaredhanson : Can you tell me what I'm missing in the above snippet?

**Comment by Altiano** [comment]
I just want to clarify something, If I want to use `passport-facebook` to behave like `passport-jwt` that can make certain routes requiring authentication, I need to always set `callbackURL`?

If so, then how should I configure the field `SiteURL` in `website` platform in `developers.facebook.com`?

**Comment by davidfurlong** [comment]
For anyone having issues even with @raosushant 's answer giving a `FacebookTokenError: Error validating verification code. Please make sure your   redirect_uri is identical to the one you used in the OAuth dialog request`, the solution is to `encodeURIComponent` the callback query string! My string had slashes, and Facebook requires redirect URL parameter to be encoded 

```js
router
  .get('/', passport.authenticate('facebook', {
    scope: ['email', 'user_about_me'],
    callbackURL: '/auth/facebook/callback?myQuery=' + encodeURIComponent(req.query.myQuery),
    failureRedirect: '/signup',
    session: false
  }))

router.get('/callback', function(req, res, next) {
  passport.authenticate(
    'facebook', {
      callbackURL: '/auth/facebook/callback?myQuery=' + encodeURIComponent(req.query.myQuery),
      failureRedirect: '/signup',
      session: false
  })(req, res, next);
}, setTokenCookie);
```

**Comment by idonov** [comment]
callbackURL is not an option anymore in 
passport.authenticate(
    'facebook', {
      callbackURL: '/auth/facebook/callback?myQuery=' + encodeURIComponent(req.query.myQuery),
      failureRedirect: '/signup',
      session: false
  })


Can this still be done somehow?

**Comment by mongkuen** [comment]
Just to leave a comment on this because it's not documented: but looking at the source there is a `successReturnToOrRedirect: string` option. Setting it does the following:

1. During authenticate - looks at your session for a `returnTo` key
2. If it exists, redirect to the location `returnTo` specifies, and delete the key from session
3. If it doesn't, redirect to the string specified in the `successReturnToOrRedirect` option

I used it in my app like so: 

```JSX
// In your signin link add a redirect query
<a href={`${TWITTER_AUTH}?redirect=%2Fsomepage`}>Sign in with twitter</a>
```

```typescript
// When you get the request on your server, set the redirect query on the session's returnTo
server.get(TWITTER_AUTH, (req, res, next) => {
  req.session = {
    returnTo: req.query.redirect,
  }
  passport.authenticate('twitter')(req, res, next)
})
```

```typescript
// On your callback set the option to use the session returnTo, or redirect to a default route
server.get(
  TWITTER_CALLBACK,
  passport.authenticate('twitter', { successReturnToOrRedirect: HOME })
)
```

**Comment by sethmichaelking** [comment]
> passport-facebook@0.1.3 (just released) now accepts a `callbackURL` option to `passport.authenticate()`.
> 
> Example:
> 
> ```
> passport.authenticate('facebook', { callbackURL: 'https://www.example.net/auth/example/callback?foo=bar' });
> ```
> 
> It can even be relative, in which case Passport will make sure it has the correct host and protocol according to the request:
> 
> ```
> passport.authenticate('facebook', { callbackURL: '/auth/example/callback?foo=bar' });
> ```
> 
> Enjoy!

Hi Jared,

I've tried what you mentioned above with the following code.

In the code snippet, I pass the state as a query in the callback an this leads to 2 problems. 

I can't access a done or cb function and the error is, "TypeError: done is not a function at Strategy._verif", which means I'm unable to complete the authentication since I just get stuck in loading on the twitter oAuth page. I'm fine with getting the val from the req.query.state, but how can I complete the process without accessing the done function or completing the process? Any advice/suggestions here would be awesome. 


// passport twitter
passport.use(new TwitterStrategy(
    {
      consumerKey: "xxl",
      consumerSecret: "x",xx
      callbackURL: "http://www.localhost:8080/auth/twitter/callback",
      passReqToCallback: true,
      includeEmail: true,
    },
    async(req, accessToken, tokenSecret, profile) => {
      // console.log(accessToken, tokenSecret, refreshToken, profile, req.query)
      const username = profile.username
      const id = req.query.state
    

     //cant access done function, what do I do here?


    }
  )
);

app.get('/auth/twitter/:id', (req, res, next) => {
  const id = req.params.id
  passport.authenticate("twitter", {
    callbackURL: `/auth/twitter/callback?state=${id}`,
  })(req, res, next)
})

app.get(
  "/auth/twitter/callback",
    passport.authenticate("twitter", {
      failureRedirect: "/login",
      failureMessage: true,
      session: false
    }),
    (req, res) => {
      console.log('here')
    res.redirect('/AccountSettings')
  }
);
