### ISSUE TITLE
redirect to OAuth Dialog problems

### ISSUE THREAD

**Issue by Jimflip** [jaredhanson/passport-facebook#21]
This did previously work for me, now doing some test it seems to have stopped working.
Users already authenticated still work okay.

When passport does the redirect back to the dialog i get the following error:

"Refused to display document because display forbidden by X-Frame-Options."

My investigations have lead me to:

https://developers.facebook.com/docs/authentication/canvas/

and specifically:

"Because your application is being loaded in an iframe, returning a 302 to redirect the user to the OAuth Dialog will be unsuccessful. Instead you must redirect by setting the Javascript window.top.location property, which causes the parent window to redirect to the OAuth Dialog URL"

I'm a little confused at this point, is this something passport-facebook should be doing, I should be doing or is there some other issue here?

**Comment by lexoyo** [comment]
FYI [I posted a workaround on stackoverflow](http://stackoverflow.com/questions/26021090/node-passport-facebook-login-in-facebook-page-tab-application/29966078)
