### ISSUE TITLE
my app is in public mode still getting access error

### ISSUE THREAD

**Issue by AshishkrGoyal** [jaredhanson/passport-facebook#240]
i have my app in live mode but still getting this err message !

`Your app is not configured. This app is still in development mode, and you don't have access to it. Switch 
 to a registered test user or ask an app admin for permissions.`

anykind of help is appreciated !
Thanks!

**Comment by AshishkrGoyal** [comment]
@jaredhanson  solved !

**Comment by Martii** [comment]
@AshishkrGoyal 

How did you solve this please?
