### ISSUE TITLE
Pass display=popup to Facebook Authentication

### ISSUE THREAD

**Issue by Radagaisus** [jaredhanson/passport-facebook#29]
Hi,

Facebook shows a different allow dialog based on a GET parameter: `display=popup`. I dug through the code and couldn't find a gentle place to add it. There are no options for passing more GET parameters to the authorization dialog, and even the oAuth package doesn't seem to accept and stringify more parameters.

A very hacky solution I found was to set the `authorizationURL` option with the `display=popup` and add another fake parameter. It's really bad and ugly but it works:

``` coffee
authorizationURL: "https://www.facebook.com/dialog/oauth?display=popup&pip"
```

Looking for ideas on how we can change `passport-facebook` to add this get parameters without writing those hacks.

**Comment by manakor** [comment]
+1

**Comment by WORMSS** [comment]
Has this documentation been removed? As I do not see this "display popup" you guys are talking about?

**Comment by timdorr** [comment]
@WORMSS It was removed in ff342984. Why? I haven't a clue...

**Comment by manakor** [comment]
@jaredhanson, why "Display mode" was removed from the documentation in ff34298? 

I feel it's still possible to use `display: 'page' || 'popup' || 'touch'` option in [`authenticate()` method](https://github.com/jaredhanson/passport-facebook/blob/master/lib/strategy.js#L73) `options` parameter. So opening authentication page in popup works, but not documented anymore…

**Comment by happy2share** [comment]
Can anyone suggest how this can be resolved? Still display: 'popup' not working.
