### ISSUE TITLE
Get Friends

### ISSUE THREAD

**Issue by ghost** [jaredhanson/passport-facebook#32]
How to get Friends?

**Comment by rolivav** [comment]
Sorry for writing on a long dead issue, but for anyone still wondering about this, this now works.
```
passport.use('facebook', new FacebookStrategy({
		clientID: ...,
		clientSecret: ...,
		callbackURL: ...,
		scope: ['user_friends'],
		profileFields: ['friends']
}
```
You'll only get the friends that have the app installed, by design.
