### ISSUE TITLE
FB connect Unauthorized source IP address

### ISSUE THREAD

**Issue by elbalu** [jaredhanson/passport-facebook#36]
Hi, 
I am getting the below error. FB connect in local is working fine but in server the error occurs.

500 failed to fetch user profile (status: 400 data: {"error":{"message":"(#5) Unauthorized source IP address","type":"OAuthException","code":5}})

**Comment by divyanshu013** [comment]
If anyone has this issue with heroku, then the best way to resolve would be to restart all your dynos. You should be allocated a new ip address and the problem should get resolved.

**Comment by Dorian** [comment]
@divyanshu013 Restarting my dynos doesn't fix it, but when I'm in a one-off dyno (e.g. `rails console`) it works fine. I will ask Heroku support.
