### ISSUE TITLE
Error: no strategy registered under name: facebook

### ISSUE THREAD

**Issue by krokhale** [jaredhanson/passport-facebook#38]
```
OpenIDStrategy = require('passport-openid').Strategy
FacebookStrategy = require('passport-facebook').Strategy
User = require('../models/user')

passport.use new OpenIDStrategy(
  returnURL: "http://localhost:5000/auth/openid/return"
  realm: "http://localhost:5000/"
  profile: true
, (identifier, profile, done) ->
  User.findOne
  open_identifier: identifier
, (err, user) ->
  unless user
    User.findOne {email_id: profile.emails[0].value}, (err, user) ->
      if user
        new_user = user
      else
        new_user = new User({first_name: profile.givenName, open_identifier: identifier,       last_name: profile.familyName, email_id: profile.emails[0].value, password: 'temptemp0101'})
        new_user.save()
      done(null, new_user)
  else
    done(null, user)
```

  )

  passport.use new FacebookStrategy(
    clientID: '3818lalala1928213'
    clientSecret: '2858bacd542a61a4325lalalac8'
    callbackURL: "http://localhost:5000/auth/facebook/callback"
  ), (accessToken, refreshToken, profile, done) ->
    console.log "yay"
    console.log profile
    done(null, 'a')

Now when i do a console.log passport, this is what i get

```
{ _key: 'passport',
  _strategies: 
{ session: { name: 'session' },
 openid: 
{ name: 'openid',
     _verify: [Function],
     _profile: true,
     _pape: undefined,
     _passReqToCallback: undefined,
     _relyingParty: [Object],
     _providerURL: undefined,
     _identifierField: 'openid_identifier' },
  '[object Object]': [Function] },
```

   _serializers: [ [Function] ],
   _deserializers: [ [Function] ],
   _infoTransformers: [],
   _framework: null,
   _userProperty: 'user',
   version: '0.1.17',
   Passport: [Function: Passport],
   Strategy: [Function: Strategy],
   strategies: { SessionStrategy: { [Function: SessionStrategy] super_: [Function: Strategy] }     } }

As you will notice there is no 'facebook' strategy in the list of strategies. Any idea what could be wrong?

**Comment by Mayank1992** [comment]
{ name: 'facebook',
  _verify: [Function],
  _oauth2: 
   { _clientId: '842179229183826',
     _clientSecret: 'f41638ebc98cf66b85e46ba149de16a0',
     _baseSite: '',
     _authorizeUrl: 'https://www.facebook.com/v2.2/dialog/oauth',
     _accessTokenUrl: 'https://graph.facebook.com/oauth/access_token',
     _accessTokenName: 'access_token',
     _authMethod: 'Bearer',
     _customHeaders: {},
     _useAuthorizationHeaderForGET: false },
  _callbackURL: 'http://localhost:3000/api/v1/auth/facebook',
  _scope: undefined,
  _scopeSeparator: ',',
  _state: undefined,
  _key: 'oauth2:www.facebook.com',
  _trustProxy: undefined,
  _passReqToCallback: true,
  _skipUserProfile: false,
  _clientSecret: 'f41638ebc98cf66b85e46ba149de16a0',
  _enableProof: undefined,
  _profileURL: 'https://graph.facebook.com/v2.2/me',
  _profileFields: null }

**Comment by Mayank1992** [comment]
after printing fb i am getting this

**Comment by Mayank1992** [comment]
and the problem is that after using passport.use('facebook',new FacebookStrategy({
appid...
clientid...
},
//not returning the facebook token and profile
function(access_token, refresh_token, profile, done){
//not coming in this function

}
))


can you help!!!!
