### ISSUE TITLE
Is there a way for FacebookStrategy to pick up clientid and secret dynamically?

### ISSUE THREAD

**Issue by jmsktm** [jaredhanson/passport-facebook#51]
I want to set the two below values dynamically:

clientID: FACEBOOK_APP_ID,
    clientSecret: FACEBOOK_APP_SECRET,

I tried something like below:

app.get('/auth/facebook',
  passport.authenticate('facebook', { clientID:"xxx", clientSecret:"yyy"}));

On running the application, when I sign in with facebook, I see that the values set above are present in options, and are getting displayed.

FacebookStrategy.prototype.authorizationParams = function (options) {
console.log("options: "+JSON.stringify(options));
var params = {},
display = options.display,
auth_type = options.auth_type;
clientID = options.clientID;
clientSecret = options.clientSecret;
if (display) params['display'] = display;
if (auth_type) params['auth_type'] = auth_type;
if (clientID) params['clientID'] = clientID;
if (clientSecret) params['clientSecret'] = clientSecret;
console.log("params: "+JSON.stringify(params));
return params;
}

Now I want to be able to set these values passed dynamically to FACEBOOK_APP_ID and FACEBOOK_APP_SECRET. Please guide me how that can be done.

Thank you.

**Comment by Benew** [comment]
Hey @jmsktm & @jaredhanson ! Has there been any progress on your end?
I'm building an back-end that manages app contents and auth. Apps can be created via an admin interface, so I need to implement new strategies on the fly. Not on a per request basis though.
Any input on that?
Thx in advance!
