### ISSUE TITLE
Can't get user profile photos.

### ISSUE THREAD

**Issue by ivadenis** [jaredhanson/passport-facebook#80]
Hi all,
I can't get the fb user photos as a profile field. Here is my code:

config.js

```
 passport.use(new FacebookStrategy({
      clientID: config.facebook.clientID,
      clientSecret: config.facebook.clientSecret,
      callbackURL: config.facebook.callbackURL
    },
    function(accessToken, refreshToken, profile, done) {
      console.log(profile)
      User.findOne({ 'facebook.id': profile.id }, function (err, user) {
        if (err) { return done(err) }
        if (!user) {
          user = new User({
            name: profile.displayName,
            email: profile.emails[0].value,
            username: profile.username,
            provider: 'facebook',
            facebook: profile._json,
            photos: profile.picture
          })
          user.save(function (err) {
            if (err) console.log(err)
            return done(err, user)
          })
        }
        else {
          return done(err, user)
        }
      })
    }
  ))
```

router.js

```
  app.get('/auth/facebook',
    passport.authenticate('facebook', {
      display: 'popup',
      scope: [ 'email', 'basic_info', 'user_photos'],
      profileFields: ['id', 'displayName', 'photos', 'emails', 'birthday'],
      failureRedirect: '/login'
    }), users.signin)
```

**Comment by sidonaldson** [comment]
This works - however you cannot user 'picture.type(large)' and 'photos' together

**Comment by josephmilla** [comment]
`FacebookGraphAPIError: (#12) username field is deprecated for versions v2.0`

Just remove `username`

**Comment by kwinrowjr** [comment]
how do you actually pass the photo into a ejs template?

**Comment by ravisuhag** [comment]
```
<%= img_tag(profile.photo) %>
```

**Comment by kwinrowjr** [comment]
ReferenceError: C:\Users\MyComp\Desktop\Project\views\profile.ejs:46
44|                     <strong>email</strong>: <%= user.facebook.email %><br>
45|                     <strong>name</strong>: <%= user.facebook.name %>
46|                     <%= img_tag(profile.photo) %>
47|                 </p>
48|
49|             </div>

img_tag is not defined
Code:
            passport.use(new FacebookStrategy({
	    clientID: configAuth.facebookAuth.clientID,
	    clientSecret: configAuth.facebookAuth.clientSecret,
	    callbackURL: configAuth.facebookAuth.callbackURL,
	    profileFields: ['email', 'displayName', 'photos']
	  },
	  function(accessToken, refreshToken, profile, done) {
	    	process.nextTick(function(){
	    		User.findOne({'facebook.id': profile.id, picture: profile.photos ? profile.photos[0].value : '/img/faces/unknown-user-pic.jpg'}, function(err, user){
	    			if(err)
	    				return done(err);
	    			if(user)
	    				return done(null, user);
	    			else {
	    				var newUser = new User();
	    				newUser.facebook.id = profile.id;
	    				newUser.facebook.token = accessToken;
	    				newUser.facebook.name = profile.displayName
	    				newUser.facebook.email = profile.emails[0].value,
	    				newUser.facebook.picture = profile.photos[0].value; //is this correct?

	    				newUser.save(function(err){
	    					if(err)
	    						throw err;
	    					return done(null, newUser);
	    				})
	    				console.log(profile);
	    			}
	    		});
	    	});
	    }

	));

**Comment by himanshuuraj** [comment]
Hi, Can you please tell me how to get the friends list...

**Comment by WIEM-S** [comment]
can you tell how to get the list of pages that the user is admin...

**Comment by sandrocsimas** [comment]
@WIEM-S 
````javascript
scope: ['manage_pages'],
````
