### ISSUE TITLE
Requesting Fields in Profile

### ISSUE THREAD

**Issue by sw360cab** [jaredhanson/passport-facebook#9]
is it possible to request additional parameters for user profile as specified in official doc http://developers.facebook.com/docs/reference/api/user/  

e.g.
Picture -> The URL of the user's profile pic (only returned if you explicitly specify a 'fields=picture' param)

Is it a possible enhancement or you already planned to handle this?
I can give look iBTW

**Comment by zloyded** [comment]
code:
passport.use(new FacebookStrategy({
    // clientID, clientSecret and callbackURL
    profileFields: ['id', 'displayName', 'photos']
  },
  // verify callback
));
Try do like this, will not working :facepunch:

**Comment by nitishatambi** [comment]
I created new account on facebook with my phone number, now I don't have email id in that account, now I want to do facebook login with my phone number, then its giving an error. Do we have any profileFields Attribute for facebook login in passport?
