### ISSUE TITLE
FacebookTokenError

### ISSUE THREAD

**Issue by toddbluhm** [jaredhanson/passport-facebook#93]
I have been using passport-facebook in my app for many months now, and just now I have run into this issue. I sort of understand what this issue means, but I am confused as to why its just now happening and how to fix it. I noticed someone else mention a similar issue and they just forgot to call ```done()``` in their auth handler. I double checked my auth handler to make sure I was calling it, and sure enough, I am calling it. I did recently upgrade to using Express4, and I am using the latest version of passport 0.2.0. Any help or direction on where to look would be appreciated. Thanks!

Passport-Facebook Error:
```
FacebookTokenError: This authorization code has been used.
    at Strategy.parseErrorResponse (/mnt/data/1/node_modules/passport-facebook/lib/strategy.js:198:12)
    at Strategy.OAuth2Strategy._createOAuthError (/mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:345:16)
    at /mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:171:43
    at /mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
    at passBackControl (/mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:124:9)
    at IncomingMessage.<anonymous> (/mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at /mnt/data/1/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31
    at /mnt/data/1/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31
  Metadata:
    [32mstack: [39m
      [32m- [39mFacebookTokenError: This authorization code has been used.
      [32m- [39m    at Strategy.parseErrorResponse (/mnt/data/1/node_modules/passport-facebook/lib/strategy.js:198:12)
      [32m- [39m    at Strategy.OAuth2Strategy._createOAuthError (/mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:345:16)
      [32m- [39m    at /mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:171:43
      [32m- [39m    at /mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
      [32m- [39m    at passBackControl (/mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:124:9)
      [32m- [39m    at IncomingMessage.<anonymous> (/mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
      [32m- [39m    at IncomingMessage.emit (events.js:117:20)
      [32m- [39m    at _stream_readable.js:929:16
      [32m- [39m    at /mnt/data/1/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31
      [32m- [39m    at /mnt/data/1/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31
    [32mname: [39m   FacebookTokenError
    [32mmessage: [39mThis authorization code has been used.
    [32mtype: [39m   OAuthException
    [32mcode: [39m   [34m100[39m
    [32mstatus: [39m [34m500[39m
FacebookTokenError: This authorization code has been used.
    at Strategy.parseErrorResponse (/mnt/data/1/node_modules/passport-facebook/lib/strategy.js:198:12)
    at Strategy.OAuth2Strategy._createOAuthError (/mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:345:16)
    at /mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:171:43
    at /mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
    at passBackControl (/mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:124:9)
    at IncomingMessage.<anonymous> (/mnt/data/1/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at /mnt/data/1/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31
    at /mnt/data/1/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31
```

My auth handler:
```javascript
exports.setupFacebookAuth = function setupFacebookAuth() {
    this.passport.use(new FacebookStrategy({
        clientID: config.FACEBOOK_APP_ID,
        clientSecret: config.FACEBOOK_APP_SECRET,
        callbackURL: config.FACEBOOK_callbackURL,
        passReqToCallback: true,
    }, function(req, accessToken, refreshToken, profile, done) {
        process.nextTick(function() {
            if (profile.hasOwnProperty('emails') && profile.emails.length > 0) {
                var userData = {
                    email: profile.emails[0].value,
                    method: 'facebook',
                    id: profile.id,
                    mixpanelID: null
                };
                //check to see if we have a mixpanel cookie
                if (req.cookies.hasOwnProperty('mp_userID') && req.cookies.mp_userID) {
                    userData.mixpanelID = JSON.parse(req.cookies.mp_userID).distinct_id;
                }

                var query = Account.findOne()
                    .where('email').equals(userData.email);

                if (!req.session.signup) {
                    query.where('facebookID').equals(userData.id);
                }

                query.execQ()
                    .then(function(account) {
                        if (account && !req.session.signup) {
                            userData.mixpanelID = account.mixpanelID || userData.mixpanelID;
                            if (config.EnableMixpanel) {
                                mixpanel.track("login", {
                                    distinct_id: account.mixpanelID,
                                    method: 'facebook',
                                    location: config.mixPanelLocation
                                });
                                mixpanel.people.increment(account.mixpanelID, "facebook");
                                mixpanel.people.set(account.mixpanelID, "last_login", new Date());
                            }
                            var resaveAccount = false;
                            if (!account.facebookID) {
                                account.facebookID = userData.id;
                                resaveAccount = true;
                            }
                            if (!account.mixpanelID) {
                                account.mixpanelID = userData.mixpanelID;
                                resaveAccount = true;
                            }
                            if (resaveAccount) {
                                account.saveQ();
                            }
                            userData.accountID = account._id;
                            return done(null, userData);
                        } else {
                            return done(null, userData, {
                                message: 'No Account Exists'
                            });
                        }
                    })
                    .fail(function(err) {
                        return done(err, null);
                    })
                    .done();
            } else {
                done(null, false, {
                    message: 'No Email Associated'
                });
            }
        });
    }));
};
```

My routes:
```javascript
router.route('/facebook/return*')
.get(function(req, res, next) {
    passport.authenticate('facebook', function(err, user, info) {
        return LogUserIn(req, res, next, err, user, info);
    })(req, res, next);
});

//facebook login url
router.route('/facebook*')
.get(passport.authenticate('facebook', {
    scope: 'email'
}));
```

**Comment by colinskow** [comment]
I was running into the same error message and found it was caused by Typeahead in the web browser. If my Facebook callback URL was .`example.com/auth/facebook/callback`, Safari and Chrome can fire automatic requests when a user types `example.com` into the URL bar, using an old authorization code if it is in their browser history. I believe this is only a problem with with a session-less setup.

Two solutions I thought of are to set a cookie with the authorization code, to not allow it to repeat, or keep track of the authorization codes server side (with Redis etc.) to end the request before Passport picks it up.

**Comment by colinskow** [comment]
I believe the best solution is actually for Passport-Facebook to check the Referrer URL in the auth callback and ensure that the request is coming from Facebook. If the request doesn't come from Facebook, then its most likely Typeahead spam from the browser history and should be ignored with a status 400. This would enhance security and cut down on wasted server resources in a large-scale app.

**Comment by bgSosh** [comment]
Same issue occurring here.  Agree with @colinskow 's solution.

**Comment by derekang** [comment]
any updates to this? facing this issue too.

**Comment by jdomingos** [comment]
What solved it for me was enabling enableProof: true in the strategy.

> passport.use(new FacebookStrategy({
  clientID: ---,
  clientSecret: ---,
  callbackURL: "http://---/auth/facebook/callback",
  enableProof: true
}

hope it helps.

**Comment by kobayakid** [comment]
hi, guys i just ran into this problem, i just restart my laptop and now it's working, has anybody seen this behavior before? i have done several thing but nothing seems to work and sometimes it just stop working.

thank you in avance!

**Comment by anneb** [comment]
I spent a lot of time on this one, because I did not read the question carefully enough. The question mentions:

I noticed someone else mention a similar issue and they just forgot to call done() in their auth handler

Check all program flows and make sure that handler:

function(req, token, refreshToken, profile, done)

always calls done when done!

**Comment by mikeuduc** [comment]
I'm getting the same error only on the facebook callback authorize middleware.  If I remove the facebook authorize middleware from my GET /auth/facebook/callback, I do not get an error (but obviously that route has no authorization). Here is my code:

Facebook Strategy
```javascript
passport.use('facebook', new FacebookStrategy({
    clientID     : configAuth.facebookAuth.clientID,
    clientSecret  : configAuth.facebookAuth.clientSecret,
    callbackURL     : configAuth.facebookAuth.callbackURL,
    passReqToCallback : true,
    enableProof: false,
    session: false,
},
function(req, accessToken, refreshToken, profile, done) {
    if(req.user !== undefined){
      req.user.facebook.id = profile.id;
      req.user.facebook.name = profile.displayName;
      req.user.facebook.token = accessToken;
      req.user.save(function(err){
        if(err) done(err);
        done(null, req.user);
      });

    }
    else{
      done(new Error('User not logged in'));
    }
}));
```

Initial Facebook Authorize/connect route
```javascript
	app.get('/auth/facebook/:shortCompanyId', 
		function(req, res, next){
			passport.authorize(
				'facebook', 
				{ 
					scope : ['email', 'publish_actions', 'user_posts'],
					state: req.params.shortCompanyId,
				}
			)(req,res,next);
		}	
	);
```
Facebook Callback route
```javascript
app.get('/auth/facebook/callback', 
		passport.authenticate(
			'facebook', 
			{ 
				successRedirect : accountController.facebookRedirect,
				failureRedirect: function(req, res, next){
					console.log('failed authentication');
					next();
				}
			}
		)
		//accountController.facebookRedirect,
	);
```

Error stack trace 
```
FacebookTokenError: This authorization code has been used.
    at Strategy.parseErrorResponse (/Users/michael/Development/crew/node_modules/passport-facebook/lib/strategy.js:200:12)
    at Strategy.OAuth2Strategy._createOAuthError (/Users/michael/Development/crew/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:345:16)
    at /Users/michael/Development/crew/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:171:43
    at /Users/michael/Development/crew/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:176:18
    at passBackControl (/Users/michael/Development/crew/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
    at IncomingMessage.<anonymous> (/Users/michael/Development/crew/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:142:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
GET /auth/facebook/callback?code=AQAMlyZQ9jFcXvwPsynRwkMZNGkkv0iTWyC4KE0Svxt2th-aiUOg8hlGPE4a0lnq_u5Ak49dt9Osf142YPD9pqaK9WUk_YhOj8UrW5-44E0bCe2IclcC0ap3nCL9EynTtgniZOZzkwf8163sOWxQno7SfZ7tguC-thX34uCx7Zy3eWFHBaW_Oeaqh_9OhS1x2SgPi8av6J99oPzX0KfJ_2X-IRpR8-Dri8LTYnX00URiyTLcPUX7vlEQVuUM87HNablKcAgHMvtrOBIMUa6o58gbAgb49lBcrPZ2MLMj5758YvUmxpm7dW9Du5UcUJ9coJ8&state=callback 500 588.983 ms - 0
```

I should add that the failureRedirect doesn't seem to work either as noted in https://github.com/jaredhanson/passport-facebook/issues/100

**Comment by pronebird** [comment]
Can't catch this error either...

**Comment by flaviolivolsi** [comment]
@jdomingos solution seems to work. Thanks!

**Comment by Connoropolous** [comment]
@jdomingos the solution also worked for me :) I don't know why, but I can't say that I really hugely care right at this moment.

**Comment by jdomingos** [comment]
Seen it here. 
https://developers.facebook.com/docs/graph-api/securing-requests#appsecret_proof

> Require proof on all calls
> In the Advanced section of your app's settings, you can require use of appsecret_proof. When this is enabled, we will only allow API calls that either include appsecret_proof or are made from the same device the token was issued to.

I have it activated in my app.
So it assumed the second call on that auth code was a "bad guy".
> (...) require proof on all calls (...) prevents **bad guys** from making API calls with your access tokens from their servers - Facebook Graph API

**Comment by vedraan** [comment]
I think @mkemalsan is right. This is not a problem with passport.js, you just need to implement error handling in the way he suggested. 
You would encounter the same error using Facebook SDK if trying to authorize an already authorized user. If it's possible for users of your app to try to re-auth even if already authenticated (which should not be possible in the first place), then you must implement error handling.
I followed @mkemalsan advice and found that the design of my social login component was bad, I should have first checked if user is already logged in via facebook before allowing auth request to go out to facebook again.

**Comment by toddbluhm** [comment]
So there are some great responses on this issue and lots of possible solutions for this situation. I am going to close this issue as I no longer need to solve this problem (have since moved on to many other projects), but if you are still having issues, I recommend you open your own issue with your specific details and problems. If you wish to add other possible solutions or clarifications feel free to do so. It would be nice if passport-facebook could some how either handle it or make the error catchable, but as many have said this issue is more a usage issue than a bug. If you disagree, then feel free to open your own issue and link back to this one.

**Comment by rw3iss** [comment]
So the answer is that we have to request an extended token, through a second request. This would obviously incur a longer response time for the user, but maybe there is a way the Facebook strategy could detect this necessity and only emit one request, for the extension. 
https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension
I've tested this locally with a manual request to the oauth/access_token endpoint, and it seems to give back a proper access_token. I will see about implementing a bandaid solution into the strategy, but for now, that is probably what is going on for the most part here.

**Comment by emorling** [comment]
@rw3iss any code you can share on this issue, would be helpful. Thx

**Comment by Siva1432** [comment]
Hello Friends, I faced the same issue in my app.  It happens because of errors in facebook callback function. When i faced this issue I invoked done(null,profile) directly. it worked. But when invoked the done function inside the query function then it gave this error. So try invoking the done(null,profile); directly without querying though the db.If it works for you then it clearly indicates that there is an error in the code before invoking the done function. Then try to fix the error and then invoke the done function. 



`passport.use({
clientId:" -----",clientSecret:"-----",callbackURL:"http://localhost:PORT/auth/facebook/callback"},
(accessToken,refreshToken,profile,done)=>{

//check your console you will find the accessToken and refresh Tokens 
console.log("Your accessToken is :"+accessToken);
console.log("Your refreshToken is :"+refreshToken );
done(null,profile);

});`

**Comment by andrewburgess** [comment]
I'm late to the party but was pulling my hair out for a good while over this. I eventually figured out what was happening though.

Basically, both route handlers (the primary one and the callback one) were being hit on the Facebook callback.

I had configured them as:

```
router.get(/(facebook|twitter)/, ...);

router.get(/(facebook|twitter)\/callback/, ...);
```

Unfortunately, I didn't realize that both route handlers were being triggered when the call to `/facebook/callback` was made. This basically passed the request through `passport.authenticate` twice. 

Reworking the route definitions fixed this issue for me (basically reordering them since I end the response in the `callback` route handler)

**Comment by waskito** [comment]
@andrewburgess I still have an issue

```
05:17:15 1|catalogu | FacebookTokenError: This authorization code has been used.
05:17:15 1|catalogu |     at Strategy.parseErrorResponse (/app/node_modules/passport-facebook/lib/strategy.js:196:12)
05:17:15 1|catalogu |     at Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:376:16)
05:17:15 1|catalogu |     at /app/node_modules/passport-oauth2/lib/strategy.js:166:45
05:17:15 1|catalogu |     at /app/node_modules/oauth/lib/oauth2.js:191:18
05:17:15 1|catalogu |     at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)
05:17:15 1|catalogu |     at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
05:17:15 1|catalogu |     at emitNone (events.js:91:20)
05:17:15 1|catalogu |     at IncomingMessage.emit (events.js:185:7)
05:17:15 1|catalogu |     at endReadableNT (_stream_readable.js:974:12)
05:17:15 1|catalogu |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
05:17:15 1|catalogu |     at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
```

here is my code:

```
// The middleware to set up the parameters for the authenticate middleware.
function checkReturnTo(req, res, next) {
  var returnTo = req.query['returnTo'];
  if (returnTo) {
    // Maybe unnecessary, but just to be sure.
    req.session = req.session || {};
    
    // Set returnTo to the absolute path you want to be redirect to after the authentication succeeds.
    //console.log(querystring.unescape(returnTo))
    req.session.returnTo = querystring.unescape(returnTo);
  }
  next();
}

app.get('/auth/facebook', checkReturnTo,
  passport.authenticate('facebook',{scope: ['public_profile, email, user_birthday']}),
);
app.get('/facebook/callback',
  passport.authenticate('facebook', { 
       scope: ['public_profile, email, user_birthday'],
       successReturnToOrRedirect: '/'
     }),
  function(req, res) {
    const returnTo = req.session.returnTo;
    delete req.session.returnTo;
    res.redirect(returnTo || '/');
});

app.get('/auth/google',checkReturnTo,
  passport.authenticate('google',{ scope: [ 'profile','email' ]})
);
app.get('/google/callback',
  passport.authenticate('google', { 
      scope: ['profile','email'],
      successReturnToOrRedirect: '/'
    }),
  function(req, res) {
    const returnTo = req.session.returnTo;
    delete req.session.returnTo;
    res.redirect(returnTo || '/');
});
```

Did my ordering still wrong?

**Comment by andrewburgess** [comment]
@waskito Hard to say from looking at the snippet you posted. A good place to start would be to [open a debugging session](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.59um98acj) and set breakpoints on your route handlers.

Make sure that only your callback route gets hit when Facebook redirects back to your server (and not the original `/auth/facebook` route).

**Comment by rocketspacer** [comment]
@andrewburgess which version of express are you using? Pattern prefix shouldn't be a problem for express router

**Comment by andrewburgess** [comment]
@rocketspacer I'm using v4

If you happen to do `app.use('auth/facebook', passport.authenticate(...)` instead of `app.get`, then you would end up with the routes passing through.

I just wanted to point out what was going on in my particular implementation since it was not immediately clear and was resolved by reordering my routes so that they were hit in the correct order.

**Comment by J-Kazama** [comment]
Try putting:
```
app.use(passport.initialize());
app.use(passport.session());
```
before any other app.use. I was receiving a middleware error in addition to the token being used error, and this resolved both.
