### ISSUE TITLE
Upgrading to v2.0?

### ISSUE THREAD

**Issue by gonzalodiaz** [jaredhanson/passport-facebook#99]
Hi, is there any plan to upgrade the library to v2.0?

https://developers.facebook.com/docs/apps/upgrading

Thanks!

**Comment by gierschv** [comment]
+1, the current used version is still 1.0, the last API version is now 2.2... // cc @jaredhanson

**Comment by goldfire** [comment]
+1

**Comment by makered** [comment]
Should same apply for token and profile URLs?

    tokenURL: "https://graph.facebook.com/v2.2/oauth/access_token",
    profileURL: "https://graph.facebook.com/v2.2/me"

**Comment by maxdec** [comment]
:+1:

**Comment by naartjie** [comment]
@duereg I made a comment on your PR #103. Like @makered mentioned, I think we should use `v2.2`, and update the `profileURL` as well, would you mind tweaking the PR?

**Comment by demisx** [comment]
:+1:

**Comment by jaredhanson** [comment]
Merged #110.  By default, the v2.2 API endpoints are now used.

**Comment by boutell** [comment]
Thanks!

On Tue, Mar 3, 2015 at 12:02 PM, Jared Hanson <notifications@github.com>
wrote:

> Merged #110 <https://github.com/jaredhanson/passport-facebook/pull/110>.
> By default, the v2.2 API endpoints are now used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaredhanson/passport-facebook/issues/99#issuecomment-76986702>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
